import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// 1. 프리텐다드 GOV (가변 폰트)
const pretendard = localFont({
  src: "../font/PretendardGOVVariable.ttf",
  display: "swap",
  variable: "--font-pretendard",
  weight: "45 920", 
});

// 2. 이롭게 바탕체
const iropkeBatang = localFont({
  src: "../font/IropkeBatangM.woff",
  display: "swap",
  variable: "--font-iropke",
  weight: "400 700", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} ${iropkeBatang.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}